import { Product } from './types/Product';

export const sampleProducts: Product[] = [
  {
    name: 'Nike Slim Shirt',
    slug: 'nike-slim-shirt',
    image: './images/p1.jpg',
    category: 'Shirts',
    brand: 'Nike',
    price: 120,
    countInStock: 10,
    description: 'High Quality Shirt',
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: 'Adidas Fit Shirt',
    slug: 'nike-fit-shirt',
    image: './images/p2.jpg',
    category: 'Shirts',
    brand: 'Adidas',
    price: 220,
    countInStock: 0,
    description: 'High Quality Shirt',
    rating: 4,
    numReviews: 17,
  },
  {
    name: 'Lacoste Free Pants',
    slug: 'lacoste-free-pants',
    image: './images/p3.jpg',
    category: 'Pants',
    brand: 'Lacoste',
    price: 320,
    countInStock: 4,
    description: 'High Quality Pants',
    rating: 4.5,
    numReviews: 13,
  },
  {
    name: 'Nike Slim Pants',
    slug: 'nike-slim-pants',
    image: './images/p4.jpg',
    category: 'Pants',
    brand: 'Nike',
    price: 350,
    countInStock: 15,
    description: 'High Quality Pants',
    rating: 4.8,
    numReviews: 2,
  },
];
